name: code-coverage-lab

# Trigger for master branch only
on: [ push ]


jobs:
  build-and-integration-test:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build -x test
    
    - name: Run tests
      run: ./gradlew test

    # TODO: Add Codecov (make sure to set up on codecov.io as well) 
    #       for test coverage reports
    - name: Upload coverage to Codecov
      run: gradle jacocoTestReport
    - name: Run bash
      env:
          CODECOV_TOKEN: ${{ secrets.Chris }}
      run: bash <(curl -s https://codecov.io/bash)

